### ISSUE TITLE
ErrorHandler serialization failed when no reason is provided

### ISSUE THREAD

**Issue by vbalasubramaniam** [julien-sarazin/Idylle#2]
When an action rejects an error without reason or with empty reason, the errorHandler should not print the error in the body 
```json
{"code": 400, "reason":""}
```

**Comment by julien-sarazin** [comment]
Fixed in https://github.com/julien-sarazin/Idylle/commit/ead4224e3d46e377e2e2e92ffad91f7aef5cf9f6
